# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Video' do
    
    pod 'PINRemoteImage', '~> 1.1'
    pod 'XCDYouTubeKit'

end

target 'VideoTests' do

end

